home/urls.py
from django.urls import path, include
from home import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

immocool/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from quittance import views
from home import views

admin.site.site_header = 'Immocool'
admin.site.site_title = 'Immocool admin'
admin.site.index_title = 'Gérer les locations et propriétés'
admin.empty_value_display = '**Empty**'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('quittance/', include('quittance.urls', namespace='pdf')),
]

urlpatterns += i18n_patterns(
    # These URLs will have /<language_code>/ appended to the beginning
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings



class Administrator(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='administrator_of',
    )
    address = models.CharField(max_length=250, default='None')
    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

home/forms.py
from django import forms


class ConnectionForm(forms.Form):
    username = forms.CharField(label = "Nom d'utilisateur",
        widget=forms.TextInput(attrs={"placeholder": "Nom d\'utilisateur",
        "class":"input100"}),
        error_messages={'required': 'Entrez un nom d\'utilisateur valide'}
    )
    password = forms.CharField(label = "Mot de passe",
        widget=forms.PasswordInput(attrs={"placeholder": "Mot de passe",
        "class":"input100"}),
        error_messages={'required': 'Entrez un mot de passe valide'}
    )

home/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.template import loader
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login, logout
from .forms import ConnectionForm
from .models import Administrator
from rental.models import Rental


def is_member(user):
    return user.groups.filter(name='Gestionnaires').exists()

@user_passes_test(is_member)
@login_required
def home(request):
    """ Get the homepage and display the information for the dashboard """
    if request.method == 'GET':
        dash = []
        # admin_dashboard = Administrator.objects.filter(user__last_name='test')
        admin_dashboard = Administrator.objects.filter(user__email=request.user.email)
        context = {'admin_dash': admin_dashboard}

        template = loader.get_template('home/index.html')
        return HttpResponse(template.render(context, request))

def login_user(request):
    if request.method == 'POST':
        form = ConnectionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    return render(request, 'login.html', {'form': form})
            else:
                messages.error(request, 'informations erronées')
    else:
        form = ConnectionForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    """  Logout the user """
    logout(request)
    messages.success(request, 'Vous êtes déconnecté')
    return redirect('home:login')

home/templates/home/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="fr">
    <head>
        <title>Immo Cool - Gérez vos propriétés facilement !</title>
        <meta charset="utf-8">
        <meta name="description" content="Application django de gestion immobilière" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP, DJANGO" />
        <meta name="author" content="MATXIK" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap core CSS -->
       <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
       <!-- Custom fonts for this template -->
       <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
       <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet" type="text/css">
       <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
       <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
       <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

       <!-- Custom styles for this template -->
       <link href="{% static 'home/css/agency.css' %}" rel="stylesheet">
       <link rel="stylesheet" type="text/css" href="{% static 'home/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %} ">
       <link rel="icon" href="{% static 'home/img/favicon.ico' %}">

    <!--========Custom styles for Connexion template =================================================-->
    	<link rel="stylesheet" type="text/css" href="{% static 'home/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %} ">
     	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
     	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
     	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
     	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
     	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
     	<link rel="stylesheet" type="text/css" href="{% static 'home/css/util.css' %}">
    </head>

    <body id="page-top">

      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{% url 'home:index' %}">Immo Cool</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#dashboard ">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#gestion">Gestion</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'home:logout' %}">Se déconnecter</a>
              </li>
            </ul>
          </div>
          {% endif %}
        </div>
      </nav>


      {% block corps %}
      {% endblock %}

    <!-- Footer -->
      <footer class="footer">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-4">
              <span class="copyright">MATXIK pour Immocool</span>
            </div>
            <!-- <div class="col-md-4">
              <ul class="list-inline quicklinks">
                <li class="list-inline-item">
                  <a href="#">Privacy Policy</a>
                </li>
                <li class="list-inline-item">
                  <a href="#">Terms of Use</a>
                </li>
              </ul>
            </div> -->
          </div>
        </div>
      </footer>
          <!-- Bootstrap core JavaScript -->
     <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
     <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

     <!-- Plugin JavaScript -->
     <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

     <!-- Contact form JavaScript -->
     <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
     <script src="{% static 'js/contact_me.js' %}"></script>

     <!-- Custom scripts for this template -->
     <script src="{% static 'js/agency.min.js' %}"></script>



    <!--=Custom script for connexion template =========================================================-->
      <script src="{% static 'vendor/animsition/js/animsition.min.js' %} "></script>
      <!-- <script src="{% static 'vendor/bootstrap/js/popper.js' %} "></script> -->
      <script src="{% static 'vendor/select2/select2.min.js' %} "></script>
      <script src="{% static 'vendor/daterangepicker/moment.min.js' %} "></script>
     <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %} "></script>
      <script src="{% static 'vendor/countdowntime/countdowntime.js' %} "></script>
     <script src="{% static 'js/main.js' %}"></script>

    </body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %}{% load static %}

{% block corps %}
<!-- Header -->
<header class="masthead">
  <div class="container" id="dashboard">
    <div class="intro-text">
      <div class="intro-lead-in intro-heading">Bienvenue {{ user.get_username }}!</div>
      <!-- <div class="intro-heading text-uppercase">It's Nice To Meet You</div> -->
      <!-- <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a> -->
    </div>
    <div class="dashboard">
      <h3>Dashboard</h3>
      {% for people in admin_dash %}
      <div class="admin_board">
        <p> Gestionnaire : {{ people.user.first_name }} {{ people.user.last_name }} </p>
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              {% for house in people.administrator_property.all %}
              <div class="col-lg-6 property_board">
                <a href="{% url 'admin:rental_property_change' house.id %}" >
                  <h5> {{house.name}} </h5>
                </a>
                <p>Locataires</p>
                {% for person in house.property_rental.all %}
                <div class="occupant_name">
                  {% load admin_urls %}
                  <a href="{% url 'admin:occupant_occupant_change' person.occupant.id %}" >
                    {{person.occupant}}
                  </a>
                </div>
                {% empty %}
                <div>
                  <p>Vous n'avez pas encore de locataires pour cette propriété</p>
                </div>
                {% endfor %}
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div>
          <a href="admin/">
            <div class="btn btn-primary btn-xl">
              Gérer
            </div>
            {% empty %}
            <p> Vous n'avez pas encore de propriétés </p>
          </a>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</header>

<!-- Services -->
<section class="page-section" id="gestion">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Gérer les locations</h2>
        <h3 class="section-subheading text-muted">Ajouter de nouveaux éléments pour gérer vos locations</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-3">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-primary"></i>
          <i class="fas fa-user-plus fa-stack-1x fa-inverse"></i>
        </span>
        <a href="{% url 'admin:occupant_occupant_add' %}" >
          <div class="btn btn-primary btn-xl">
            Nouveau locataire
          </div>
        </a>
      </div>
      <div class="col-md-3">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-primary"></i>
          <i class="far fa-address-card fa-stack-1x fa-inverse"></i>
        </span>
        <a href="{% url 'admin:rental_rental_add' %}" >
          <div class="btn btn-primary btn-xl">
            Nouvelle location
          </div>
        </a>
      </div>
      <div class="col-md-3">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-primary"></i>
          <i class="fas fa-home fa-stack-1x fa-inverse"></i>
        </span>
        <a href="{% url 'admin:rental_property_add' %}" >
          <div class="btn btn-primary btn-xl">
            Nouvelle propriété
          </div>
        </a>
      </div>
      <div class="col-md-3">
        <span class="fa-stack fa-4x">
          <i class="fas fa-circle fa-stack-2x text-primary"></i>
          <i class="fas fa-euro-sign fa-stack-1x fa-inverse"></i>
        </span>
        <a href="{% url 'admin:quittance_echeance_changelist' %}" >
          <div class="btn btn-primary btn-xl">
            Echéances de loyer
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

{% endblock %}